name: Metrics
on: 
  schedule: [{cron: "0 23 * * *"}]
jobs: 
  github-metrics:  
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps: 
      - name: WakaTime 
        uses: lowlighter/metrics@latest
        with: 
          filename: metrics.plugin.wakatime.svg
          token: NOT_NEEDED
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: languages, languages-graphs, editors, editors-graphs
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
      - name: Full-year Calendar 
        uses: lowlighter/metrics@latest
        with: 
          filename: metrics.plugin.isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
