name: Metrics
on: 
  workflow_dispatch:
  schedule: [{cron: "0 23 * * *"}]
jobs: 
  github-metrics:  
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps: 
      - uses: actions/checkout@v2
      - name: WakaTime 
        uses: lowlighter/metrics@latest
        with: 
          filename: metrics.plugin.wakatime.svg
          token: NOT_NEEDED
          base: ""
          plugin_wakatime: yes
          plugin_wakatime_sections: languages, languages-graphs, editors, editors-graphs
          plugin_wakatime_token: ${{ secrets.WAKATIME_TOKEN }}
      - name: generate-profile-3d-contrib
        uses: yoshi389111/github-profile-3d-contrib@0.6.0
        env:
          GITHUB_TOKEN: ${{ secrets.METRICS_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config user.name laffed
          git config user.email roarklaffed@gmail.com
          git pull
          git add -A .
          git commit -m "generated"
          git push
